export const SEARCH_INPROGRESS = 'SEARCH_INPROGRESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const SEARCH_STRING = 'SEARCH_STRING';

export const ADD_TO_PORTFOLIO_INPROGRESS = 'ADD_TO_PORTFOLIO_INPROGRESS';
export const ADD_TO_PORTFOLIO_ERROR = 'ADD_TO_PORTFOLIO_ERROR';
export const ADD_TO_PORTFOLIO_SUCCESS = 'ADD_TO_PORTFOLIO_SUCCESS';

export const ADD_TO_WATCHLIST_INPROGRESS = 'ADD_TO_WATCHLIST_INPROGRESS';
export const ADD_TO_WATCHLIST_ERROR = 'ADD_TO_WATCHLIST_ERROR';
export const ADD_TO_WATCHLIST_SUCCESS = 'ADD_TO_WATCHLIST_SUCCESS';

export const LOAD_WATCHLIST_INPROGRESS = 'LOAD_WATCHLIST_INPROGRESS';
export const LOAD_WATCHLIST_ERROR = 'LOAD_WATCHLIST_ERROR';
export const LOAD_WATCHLIST_SUCCESS = 'LOAD_WATCHLIST_SUCCESS';
